//FETCHING PRODUCT TYPES
export const FETCH_CATEGORY = 'FETCH_CATEGORY';
export const FETCH_CURRENCIES= 'FETCH_CURRENCIES';
export const FETCH_PRODUCT= 'FETCH_PRODUCT';

//CART TYPES

export const GET_NUMBER_CART='GET_NUMBER_CART'
export const ADD_CART='ADD_CART'
export const DECREASE_QUANTITY='DECREASE_QUANTITY'
export const INCREASE_QUANTITY='INCREASE_QUANTITY'
export const DELETE_CART='DELETE_CART'
export const UPDATE_CART='UPDATE_CART'